name: Go Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    # Add PostgreSQL service container
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: loanservice_test
        ports:
          - 5432:5432
        # Ensure the database is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # Use the appropriate Go version for your project

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Run tests
      env:
        # Configure test database connection
        TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/loanservice_test?sslmode=disable
      run: |
        go test ./... -v

    - name: Run race detector
      env:
        # Configure test database connection for race detector
        TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/loanservice_test?sslmode=disable
      run: |
        go test ./... -race

    - name: Run code coverage
      env:
        # Configure test database connection for code coverage
        TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/loanservice_test?sslmode=disable
      run: |
        go test ./... -coverprofile=coverage.out
        go tool cover -func=coverage.out

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.out
        fail_ci_if_error: false
        verbose: false
